version: '2'
services:
    api:
        image: node:7.10.0
        ports:
            - "5550:5550"
            - "5551:5551"
        volumes:
            - ./:/opt/www/la-vendimia-api
        working_dir: '/opt/www/la-vendimia-api'
        command:
            ./node_modules/.bin/nodemon --legacy-watch --inspect=0.0.0.0:5551 ./src/index.js
        environment:
            API_HOST: api
            API_PORT: 5550
            MONGO_HOST: mongo
            MONGO_PORT: 27017
            MONGO_PARTITION: vendimia
        networks:
            - vendimianet
    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db
        networks:
            - vendimianet
networks:
    vendimianet:
        driver: "bridge"
volumes:
    data:
        driver: "local"
